language: node_js
node_js:
  - lts/*
before_install:
  - "echo $TRAVIS_BRANCH"
install:
  - npm ci --prefix client
script:
  - npm test
  - bash travis/build.sh
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash travis/deploy.sh; fi'
git:
  depth: false
